[package]
name = "skia_window"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_glutin = { path = "../../glutin" }
iced = { path = "../..", features = ["skia", "debug"] }
